### ISSUE TITLE
roomに関するcrud操作の実装

### ISSUE THREAD

**Issue by ari1021** [ari1021/chat#21]
controller/room.go内にあるCreateRoomやGetRoomsなどの中で，以下のような処理を想定．
1. リクエストのbodyから情報を受け取り
2. db操作の関数を呼び出す

そのため，次のことを行う．
- [x] bodyから情報を受け取るようの構造体を/requestに作成する
- [x] model/room.goにroomを登録するmethodを書く
- [x] model/room.goにroomを取得するmethodを書く
- [x] 上で書いたmethodを用いるようにcontroller/room.go修正する

**Comment by konnyaku256** [comment]
"formから" の部分はGET, POSTリクエストのbodyからと書いてあるほうがいいかな～

formはWebフロントのviewに当たる部分なのでサーバ側CRUDの実装と切り離せるはず！
