### ISSUE TITLE
usersテーブルの削除とそれに伴う修正

### ISSUE THREAD

**Issue by ari1021** [ari1021/chat#28]
- [x] usersテーブルの削除
- [x] chatsテーブルからuser関連のカラムを削除
- [x] roomsテーブルからuser関連のカラムを削除
- [x] request/chatの修正
- [x] request/roomの修正

**Comment by Khmer495** [comment]
ログイン機能の削除!=ユーザーに関するもの全て削除ではないと思うので、何を残す必要があるのか精査してもらえると！
